language: python

install: pip install tox
env:
  matrix:
    # consul 0.7.5
    - TOX_ENV=py27     CONSUL_VERSION=0.7.5
    - TOX_ENV=py33     CONSUL_VERSION=0.7.5
    - TOX_ENV=py34     CONSUL_VERSION=0.7.5
    - TOX_ENV=py35     CONSUL_VERSION=0.7.5

    # consul 0.8.5
    - TOX_ENV=py27     CONSUL_VERSION=0.8.5
    - TOX_ENV=py33     CONSUL_VERSION=0.8.5
    - TOX_ENV=py34     CONSUL_VERSION=0.8.5
    - TOX_ENV=py35     CONSUL_VERSION=0.8.5

    # consul 0.9.0
    - TOX_ENV=py27     CONSUL_VERSION=0.9.0
    - TOX_ENV=py33     CONSUL_VERSION=0.9.0
    - TOX_ENV=py34     CONSUL_VERSION=0.9.0
    - TOX_ENV=py35     CONSUL_VERSION=0.9.0

    # coverage and style checks
    - TOX_ENV=pep8     CONSUL_VERSION=0.9.0
    - TOX_ENV=coverage CONSUL_VERSION=0.9.0

before_script:
  - mkdir tmp
  - wget https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
  - unzip consul_${CONSUL_VERSION}_linux_amd64.zip
  - ${TRAVIS_BUILD_DIR}/consul agent -server -data-dir tmp -bootstrap-expect=1 -bind=127.0.0.1

script:
  - CONSUL_BIN=${TRAVIS_BUILD_DIR}/consul CONSUL_DATA_DIR=tmp tox -e $TOX_ENV

notifications:
  email:
    - swistakm@gmail.com
